# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CommitGpt < Formula
  desc ""
  homepage "https://github.com/ohmpatel1997/CommitGPT"
  version "0.1.9"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ohmpatel1997/CommitGPT/releases/download/v0.1.9/CommitGPT_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "675b2e13524153583761fc61533f83fb8a7345f42bd047b1dbb871764673aca0"

      def install
        bin.install "commit-gpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ohmpatel1997/CommitGPT/releases/download/v0.1.9/CommitGPT_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "4b45e78967083fde5d2b7ca62d59a71f9ffb09e2391857ca7c6c109b5cb1c923"

      def install
        bin.install "commit-gpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohmpatel1997/CommitGPT/releases/download/v0.1.9/CommitGPT_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "4b8308cf88fcd384813efcf53300bc1be503d3221f2fb5fdc6c14a69e7bbb824"

      def install
        bin.install "commit-gpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ohmpatel1997/CommitGPT/releases/download/v0.1.9/CommitGPT_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "17de3727cbd120706a7c9a184ba52ab9f65afc3b4e03543a32752255a47793bf"

      def install
        bin.install "commit-gpt"
      end
    end
  end
end
