# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CommitGpt < Formula
  desc ""
  homepage ""
  version "0.1.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ohmpatel1997/CommitGPT/releases/download/v0.1.8/CommitGPT_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "0402367732d63a3834c8b74c35f57f89e93872571664c8c40fbdd0b8dda44fd8"

      def install
        bin.install "commit-gpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ohmpatel1997/CommitGPT/releases/download/v0.1.8/CommitGPT_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "0e22e77af9a607946ad9506dddcf42eacfccc14c4c1aaba326e0b39dae5ccb3a"

      def install
        bin.install "commit-gpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohmpatel1997/CommitGPT/releases/download/v0.1.8/CommitGPT_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "992b5341b05fa1c4c8d64ca391b0ff6f3c47b04add9db4725ea79adabecf290b"

      def install
        bin.install "commit-gpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ohmpatel1997/CommitGPT/releases/download/v0.1.8/CommitGPT_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "b666e3563b9c833c823b192b2b222badc24bd032b1d5da5c72daeb2c3226adbd"

      def install
        bin.install "commit-gpt"
      end
    end
  end
end
